version: '3'

services:
  chrome:
    image: robcherry/docker-chromedriver
    networks:
      - services
    environment:
      CHROMEDRIVER_WHITELISTED_IPS: ""
      CHROMEDRIVER_PORT: "9515"
    dns: 172.18.1.1
    shm_size: '2gb'
    cap_add:
       - "SYS_ADMIN"
