version: '3'

services:
  dnsmasq:
    image: jpillora/dnsmasq:1.1.0
    labels:
      - "traefik.port=8080"
      - "traefik.enable=true"
      - "traefik.docker.network=ops_gateway"
      - "traefik.frontend.whiteList.sourceRange=172.22.0.0/16"
      - "${OPS_ADMIN_AUTH_LABEL_PREFIX}traefik.frontend.auth.basic.users=${OPS_ADMIN_AUTH}"
    networks:
      gateway:
      backend:
      services:
        ipv4_address: 172.23.10.10
    volumes:
      - ${OPS_HOME}/dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf
